/**
 * Builds the drag-and-drop bundle: dist-upload/ and dar-al-kohl.zip.
 *
 * This is the deploy path for someone who has no terminal and no GitHub
 * account. Cloudflare Pages takes an uploaded zip in the browser, and a
 * `_worker.js` at its root takes over every request — which is exactly the
 * shape this app already has, because the Worker asks the ASSETS binding for
 * the static files itself.
 *
 * The zip holds the whole shop: the bundled Worker, the page, the stylesheet,
 * the script and the icons. Nothing else has to be installed, cloned or
 * configured beyond binding a D1 database in the dashboard.
 *
 * Run: npm run bundle
 */
import { build } from 'esbuild';
import { readdir, mkdir, rm, copyFile, stat, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'dist-upload');
const zip = join(root, 'dar-al-kohl.zip');

await rm(out, { recursive: true, force: true });
await rm(zip, { force: true });
await mkdir(out, { recursive: true });

/* --- the Worker, as one module --- */
await build({
  entryPoints: [join(root, 'src/worker.js')],
  outfile: join(out, '_worker.js'),
  bundle: true,
  format: 'esm',
  target: 'es2022',
  platform: 'neutral',
  // Readable on purpose: this file is the whole back end, and the person
  // deploying it should be able to look at what they are uploading.
  minify: false,
  banner: {
    js: '/* دار الكحل — the whole shop, bundled for a drag-and-drop deploy.\n'
      + ' * Generated by scripts/build-upload.mjs — edit src/, not this file. */',
  },
});

/* --- the shop front, beside it --- */
for (const name of await readdir(join(root, 'public'))) {
  await copyFile(join(root, 'public', name), join(out, name));
}

/* --- a note for whoever opens the zip --- */
await writeFile(join(out, 'HOW-TO-DEPLOY.txt'), `دار الكحل — Dar al-Kohl
=======================

Everything the shop needs is in this folder. No terminal, no GitHub.

1. Go to dash.cloudflare.com and sign in (a free account is enough).

2. Make the database first, so it is ready to bind:
   Storage & Databases  ->  D1 SQL Database  ->  Create
   Call it:  darkohl
   (The name does not have to match anything; only the binding below does.)

3. Compute  ->  Workers & Pages  ->  Create  ->  Pages  ->  Upload assets
   Name the project, then drag this whole folder (or the zip) in.
   Press Deploy. You will get an address ending in .pages.dev — that is
   the shop, but it cannot save anything yet.

4. Give it the database:
   the project  ->  Settings  ->  Bindings  ->  Add  ->  D1 database
   Variable name:  DB          (exactly those two letters, capitals)
   D1 database:    darkohl
   Save.

5. Deployments  ->  the deployment you just made  ->  Retry deployment.
   A binding only reaches a NEW deployment, so this step is what switches
   the shop on. It builds its own tables and stocks itself the first time
   anyone opens it.

6. Open the address, scroll to the bottom, press the small diamond, and
   sign in:
       awni7617@gmail.com
       123456
   Change that password straight away — Settings, then بيانات الدخول.
   The shop shows an orange warning until you do.

7. Put your real WhatsApp number in الإعدادات, or orders will have
   nowhere to go.

On an iPhone: open the address in Safari, press Share, then Add to Home
Screen. It gets its own icon and opens without Safari's chrome.
`);

/* --- one file to hand over --- */
try {
  execFileSync('zip', ['-r', '-q', zip, '.'], { cwd: out });
} catch {
  console.warn('zip is not installed — dist-upload/ is ready, but no archive was made.');
}

const size = async (p) => Math.round((await stat(p)).size / 1024);
console.log(`dist-upload/_worker.js — ${await size(join(out, '_worker.js'))} KB`);
try {
  console.log(`dar-al-kohl.zip     — ${await size(zip)} KB`);
} catch { /* no zip */ }
